-- q1
SELECT * FROM HR.EMPLOYEES
WHERE JOB_ID = 'SA_MAN'
ORDER BY SALARY DESC;

--Q2
SELECT FIRST_NAME ||' ' || LAST_NAME AS FULL_NAME, SALARY
FROM HR.EMPLOYEES
WHERE SALARY > 15000;

--Q3
SELECT * FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

--Q4
SELECT * FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID <> 50;

--Q5
SELECT * FROM HR.EMPLOYEES
WHERE SALARY > 10000 AND DEPARTMENT_ID = 80;

--Q6
SELECT * FROM HR.EMPLOYEES
WHERE SALARY < 5000 OR DEPARTMENT_ID = 100;

--Q7
SELECT * FROM HR.EMPLOYEES
WHERE MANAGER_ID IS NULL;

--Q8
SELECT * FROM HR.EMPLOYEES
WHERE SALARY > 10000 AND COMMISSION_PCT IS NOT NULL;

--Q9
SELECT * FROM HR.EMPLOYEES
WHERE JOB_ID NOT IN ('IT_PROG');

--Q10
SELECT * FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN (10,20,30);

--Q11
SELECT * FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID NOT IN (40,50,60);

--Q12
SELECT * FROM HR.EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 10000;

--Q13
-- January 1, 2000 and December 31, 2005
SELECT * FROM HR.EMPLOYEES
WHERE HIRE_DATE BETWEEN DATE '2000-01-01' AND DATE '2015-12-31';

--Q14
SELECT * FROM HR.EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','SA_MAN','FI_ACCOUNT');

--Q15
SELECT * FROM HR.EMPLOYEES
WHERE FIRST_NAME LIKE 'S%';

--Q16
SELECT * FROM HR.EMPLOYEES
WHERE LAST_NAME LIKE '%n';

--Q17
SELECT * FROM HR.EMPLOYEES
WHERE FIRST_NAME LIKE '%an%';

--Q18
SELECT * FROM HR.EMPLOYEES
WHERE JOB_ID LIKE '%CLERK%';

--Q19
SELECT * FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 90
ORDER BY HIRE_DATE;

--Q20
SELECT * FROM HR.EMPLOYEES
ORDER BY COMMISSION_PCT ASC;

--Q21
SELECT * FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;


--Q22
SELECT * FROM HR.EMPLOYEES
WHERE JOB_ID NOT IN ('IT_PROG','SA_REP','FI_ACCOUNT');

--Q23
SELECT * FROM HR.EMPLOYEES
WHERE MANAGER_ID = 100 OR MANAGER_ID = 101 OR MANAGER_ID = 201;

--Q24
SELECT * FROM HR.EMPLOYEES
WHERE MANAGER_ID IN (100,101,201);

--Q25
SELECT * FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

--Q26
SELECT * FROM HR.EMPLOYEES
WHERE FIRST_NAME LIKE '_o%';

--Q27
SELECT JOB_ID,FIRST_NAME, HIRE_DATE
FROM HR.EMPLOYEES
ORDER BY JOB_ID DESC, FIRST_NAME ASC;

--Q28
SELECT * FROM HR.EMPLOYEES
WHERE JOB_ID IN ('SA_REP','AD_PRES') AND SALARY > 15000;