-- LAB 2B

--Q1

SELECT UPPER(CITY) AS CITIES
FROM HR.LOCATIONS
WHERE COUNTRY_ID = 'US';

--Q2
SELECT UPPER(STREET_ADDRESS), LOWER(CITY), CITY || ' ' ||STATE_PROVINCE AS CITY_STATE_PROVINCE
FROM HR.LOCATIONS;

--Q3
SELECT * FROM HR.EMPLOYEES
WHERE LOWER(FIRST_NAME) = 'michael';

--Q4
SELECT INITCAP(FIRST_NAME) AS F_NAME, INITCAP(LAST_NAME) AS L_NAME
FROM HR.EMPLOYEES;

--Q5
SELECT FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
JOB_ID, MANAGER_ID FROM HR.EMPLOYEES;

--Q6
SELECT  * FROM HR.EMPLOYEES
WHERE SUBSTR(JOB_ID,1,2) = 'FI' OR SUBSTR(JOB_ID,4,5) = 'CLERK';

--Q7
SELECT FIRST_NAME, LAST_NAME, LENGTH(PHONE_NUMBER) AS PHONE_FORMAT, LENGTH(SALARY) AS SALARY_DIGITS
FROM HR.EMPLOYEES;

--Q8
SELECT INSTR(JOB_TITLE, ' ') FROM HR.JOBS;

-- INCLUDE THOSE WITH NO SPACES
--SELECT INSTR(JOB_TITLE, ' ') FROM HR.JOBS
--WHERE INSTR(JOB_TITLE, ' ')<> 0;

--Q9
SELECT SUBSTR(JOB_TITLE,1,1) AS FIRST_WORD_JB
FROM HR.JOBS;

--Q10
SELECT LPAD('Zara',5,'-') FROM dual;

--Q11
SELECT rPAD('Zara',5,'-') FROM dual;

--Q12
SELECT TRIM('            Zara Asim           ') FROM dual;

--Q13
SELECT LTRIM('xZara Asimx','x') FROM DUAL;

--Q14
SELECT RTRIM('xZara Asimx','x') FROM DUAL;

--Q15
SELECT REPLACE(SALARY,2600,5) FROM HR.EMPLOYEES;

--Q16
SELECT ROUND(AVG(SALARY),3) FROM HR.EMPLOYEES;

--Q17
SELECT ROUND(AVG(SALARY),0) FROM HR.EMPLOYEES; 

--Q18
SELECT TRUNC(AVG(SALARY),4) FROM HR.EMPLOYEES; 

--Q19
SELECT MOD(6,2) FROM DUAL;

--Q20
SELECT ROUND(MONTHS_BETWEEN(SYSDATE, '14-DEC-03')) AS BDAY_MONTHS FROM DUAL;

--Q21
SELECT FIRST_NAME, LAST_NAME, JOB_ID, ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,0) AS EXPERIENCE_IN_YEARS
FROM HR.EMPLOYEES;

--Q22
SELECT ADD_MONTHS('04-SEP-2025', 3) FROM DUAL;

--Q23
SELECT NEXT_DAY('01-JAN-2101', 'SUNDAY') FROM DUAL;

--Q24
SELECT ROUND(SYSDATE,'MM') FROM DUAL;

--Q25
SELECT ROUND(SYSDATE,'YY') FROM DUAL;

--Q26
SELECT TRUNC(SYSDATE,'MM') FROM DUAL;

--Q27 
SELECT TRUNC(SYSDATE,'YY') FROM DUAL;

--Q28
SELECT COUNT(HIRE_DATE) FROM HR.EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'MONTH') LIKE '%JUNE%';


