--LAB 2A

--Q1
SELECT COUNT(*) FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 50;

--Q2
SELECT COUNT(EMPLOYEE_ID) FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 80 AND SALARY > 24000;

--Q3
SELECT COUNT(EMPLOYEE_ID) FROM HR.EMPLOYEES;

--Q4
SELECT AVG(SALARY) AS AVG_SALARY, MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY
FROM HR.EMPLOYEES
WHERE JOB_ID LIKE '%CLERK'
GROUP BY JOB_ID;

--Q5
SELECT COUNT(DISTINCT DEPARTMENT_ID)
FROM HR.EMPLOYEES;

--Q6
SELECT COUNT(DISTINCT JOB_ID)
FROM HR.EMPLOYEES;

--Q7
SELECT ROUND(AVG(COMMISSION_PCT),2) AS AVG_COMMISSION FROM HR.EMPLOYEES;

--Q8
SELECT ROUND(AVG(COMMISSION_PCT),2) AS AVG_COMMISSION FROM HR.EMPLOYEES;

--Q9
SELECT TRUNC(SUM(COMMISSION_PCT)/COUNT(*),2) AS AVG_COMMISSION 
FROM HR.EMPLOYEES;

--Q10
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2) AS AVG_SALARY
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID IS NOT NULL;

--Q11
SELECT JOB_ID, AVG(SALARY)
FROM HR.EMPLOYEES
GROUP BY JOB_ID;

--Q12
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID IS NOT NULL
ORDER BY DEPARTMENT_ID;

--Q13
SELECT DEPARTMENT_ID ,AVG(SALARY)
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY AVG(SALARY) ASC
fetch first row only;

--Q14
SELECT JOB_ID, MAX(SALARY)
FROM HR.EMPLOYEES
GROUP BY JOB_ID
ORDER BY MAX(SALARY) DESC
fetch first 5 rows only;

--Q15
SELECT department_id, job_id, count(last_name)
FROM HR.EMPLOYEES
GROUP BY JOB_ID, DEPARTMENT_ID;

--Q16
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 8000;

--Q17
SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) AS SALARY_TOTAL
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING SUM(SALARY) > 10000
ORDER BY DEPARTMENT_ID;

--Q18
SELECT DEPARTMENT_ID , AVG(MONTHS_BETWEEN(end_date, start_date)) AS AVG_JOB_DURATION
FROM HR.JOB_HISTORY
GROUP BY DEPARTMENT_ID;

--Q19
SELECT JOB_ID , AVG(MONTHS_BETWEEN(end_date, start_date)) AS AVG_JOB_DURATION
FROM HR.JOB_HISTORY
GROUP BY JOB_ID;

--Q20
--Location column was not specified so I used street_address
SELECT LOCATION_ID,COUNT(STREET_ADDRESS) AS ADDRESS
FROM HR.LOCATIONS
GROUP BY LOCATION_ID;